### PR TITLE
Added Polish translation

### PR DESCRIPTION
**Pull request by econo202**

### CODE REVIEW

**Comment by thetwom** [comment]
Hi, thanks a lot for your efforts and translating the app to Polish. I did a very quick double check with Google translate and I wonder if your translation of "note" -> "notatki" matches the meaning. Google tells me it means something like "memo", while in the app"note" refers to the "musical note". Can you double check and give feedback if your translation fits as it is or if if doesn't, adapt it? 

Best regards and thanks again!

**Comment by econo202** [comment]
Hi, of course you're right! It was late and I've overlooked "note".
I'll update the PR in a moment.

**Comment by thetwom** [comment]
Thanks for the quick update. I am still a bit uncertain if you captured the correct meaning since the computer tells me something different, but please correct me if I am wrong. The computer translates the "musical note" to something like "nota" in Polish, but of course I can't tell if this is correct. Let me quickly give the meaning of the strings and then you decide what is correct:
- The meaning of "add_note" is what happens if you press the plus-button -> A musical note is added at the note lines at the bottom
-  The meaning of "cannot_delete_last_note" is, that if you try to remove the last remaining musical note, there will be a message printed, that you cannot delete it.
- The meaning of "vibrate_notes" is what you find in the settings. If you switch it on, your phone will vibrate with every note.
- The meaning of "all_notes_deleted" is that this string is printed, when you press the clear-all-button (the one which is next to the plus button). It tells you that all musical notes are deleted and you can choose to revert it ...

Best regards and thanks again for your effort!!!

**Comment by econo202** [comment]
English "note" has many meanings in Polish, but the one correct here ("musical note") in Polish is "nuta", and I've translated all the strings that way.

**Comment by thetwom** [comment]
ok, thanks for the clarification. I was just confused that I read "nutę" and "nuty" and not "nuta", but I guess this are just the correct grammatical forms ... 
thanks again for your efforts!

**Pull request merged**
