### PR TITLE
Basque translation

### PR DESCRIPTION
**Pull request by Porrumentzio**

### CODE REVIEW

**Comment by thetwom** [comment]
Thanks a lot for your translations. Currently, I am a bit reluctant with creating a new release since the latest changes were very low level and don't have the option to test it on many phones ... so it might take some more days ...

**Comment by Porrumentzio** [comment]
Thanks to you for the app!
If there are any changes to get a release, I'll please it!

**Comment by thetwom** [comment]
I  created now release [v2.4.0](https://github.com/thetwom/toc2/releases/tag/v2.4.0), which should be picked up by fdroid soon. For google play I will wait some time to make sure at least fdroid users don't have issues ...

**Comment by Porrumentzio** [comment]
Thanks! I'll say you if I see any problem, thanks for your work!

**Pull request merged**
