### PR TITLE
Finnish translations to toc2/fastlane/metadata/android

### PR DESCRIPTION
**Pull request by retki**

### CODE REVIEW

**Comment by thetwom** [comment]
Hi, thanks for the fastlane translations. Can I ask you for some changes? I would prefer if you only put "full_description.txt", "short_description.txt" and "title.txt" the "fi"-folder. All the rest will automatically be picked up from the en-US-folder. See. e.g. the "de" or the "pl" folder as an example.

**Comment by retki** [comment]
@thetwom
You're welcome. I removed the images and changelogs directory from patch-2.

When will you release an update that includes these translations?

**Comment by thetwom** [comment]
Thanks for the update, this looks great now. I can tag the release today. Until it reaches fdroid and the play store can take some days, but this is out of my control :-)

**Comment by retki** [comment]
Great 👍

**Pull request merged**
