### PR TITLE
French translation, first proposal

### PR DESCRIPTION
**Pull request by brilnius**

### CODE REVIEW

**Comment by thetwom** [comment]
Hi, thanks a lot for your translations!
I did some minor corrections to fit the current style:
- For now I don't translate the app name, not sure if I better should revise this decision in future.
- The different drum names do not yet require translations, since they are not visible to the user.
- I added some escape characters and removed some spaces. Let me know if I corrected something you did on purpose.
About the translations that aren't currently needed, I commented theses lines out. But I might reintroduce them in future.

You find my changes in the brilnius-master branch. 
Let me know, what you think about my "corrections" and I will include the translations.

**Comment by brilnius** [comment]
Hello.

Thanks for reviewing and amending it.

Yes spaces before colons (:) were added on purpose. According to French typographic rules, there should be a _non-breaking_ space before and a space after.
A reference to typographic rules for French articles on Wikipedia (in French):
https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#ESPACES-PONCTUATION

But if you want my opinion, this is not important, better no space than a "breaking" space. With a breaking space, there is maybe a risk that the colon be placed at the beginning of a line (berk).

I take the opportunity to thank you (and all other developers) for the application. The "ring" for selecting the tempo is simply a great idea. :-)

**Comment by thetwom** [comment]
Thanks for the clarification about the spaces. I added now non-breaking spaces before the colons. Hopefully this works as intended. Release [v1.6.6](https://github.com/thetwom/toc2/releases/tag/v1.6.6) includes now your translations. It should appear on fdroid during the next days, but you can also try the apk I provided with the release. If you spot some problems or mistakes, please let me know ... or send another pull request.

Thanks again for your efforts in making the app better. I am glad you like it :-)

**Comment by thetwom** [comment]
Hi, I am about to publish a new version which contains several new strings. Maybe you find some time and can complete the translations (in the latest master version)?

**Comment by brilnius** [comment]
Hi. I've updated my master branch. I'm not familiar with Github, so don't hesitate to tell me if I should do things in a different way.

Also I'm not sure how the new strings will be used, so I may propose different translations after I see them in the app.
In particular I don't see the difference between load_from_disc and load_saved_items for now.

**Comment by thetwom** [comment]
Hi, thanks for the great support and the very quick translations. The way you did it is just fine. I was able to merge them locally and keep you as author (I will push them upstream soon).

Some strings only appear on very small screens, when there is not enough space for the icons in the toolbar. Then there is just an options menu, where instead of the icons the text is shown. 
I think it's fine to use your translations as they are. It's absolutely no problem to improve these later on. Please also don't hesitate to send really minor changes (even if it's just one character).

**Pull request merged**
